services:
  redis:
    image: redis:7-alpine

  aqsh:
    build: .
    environment:
      AQSH_MODE: both
      AQSH_REDIS_ADDR: redis:6379
    volumes:
      - ./tasks.yaml:/etc/aqsh/tasks.yaml:ro
      - ./tasks.d:/etc/aqsh/tasks.d:ro
      - ./tasks:/tasks:ro
    depends_on:
      - redis

  mock-values:
    image: python:3-alpine
    command: python /scripts/server.py
    volumes:
      - ./test/mock-values-server:/scripts:ro

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      AQSH_REDIS_ADDR: redis:6379
      AQSH_URL: http://aqsh:8080
      MOCK_VALUES_URL: http://mock-values:8090
      DEV_CONTAINER: "true"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - aqsh
      - mock-values
    profiles:
      - dev
